### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by Animeimp** [psi-4ward/ld382.js#1]
Running on node.js 12.6/Synology

npm WARN engine ld382.js@0.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.6","npm":"2.11.2"})
/usr/bin/ld382 -> /usr/lib/node_modules/ld382.js/bin/ld382.js
ld382.js@0.0.0 /usr/lib/node_modules/ld382.js
├── netmask@1.0.5
├── async@1.5.2
├── commander@2.9.0 (graceful-readlink@1.0.1)
└── debug@2.2.0 (ms@0.7.1)
Diskstation2> ld382 -h
/volume1/@appstore/Node.js/usr/lib/node_modules/ld382.js/lib/cli.js:2
const program = require('commander');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/volume1/@appstore/Node.js/usr/lib/node_modules/ld382.js/bin/ld382.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

I made sure all dependencies were installed first.  None of the searches seems to cover anything relating to this problem.

Diskstation2> npm ls
/root
`-- ld382.js@0.0.0
  +-- async@1.5.2
  +-- commander@2.9.0
  |`-- graceful-readlink@1.0.1
  +-- debug@2.2.0
  | `-- ms@0.7.1
`-- netmask@1.0.5

**Comment by psi-4ward** [comment]
Hey Node 0.12 is pretty old and "const" is a ES6 feature.
Please try Node > 4.0.
